
[pytest]
pythonpath = "src"
testpaths = tests


# When importing modules, treat src as if on python path
# Only look for tests inside test folder
# Tests can now import modules like:
# from src.markov_model import MarkovModel
