---
title: "FINAL_REFLECTION"
author: "Stefanie Moreno"
date: "2026-04-09"
output:
  md_document:
    variant: gfm
---

# Final Reflection

### The Memoization Goldilocks Zone: Investigating Hyperparameter Boundaries in Markov Models for Classifying Structural Features in the Human Genome.

#### Project Accomplishments

o	Specific technical and process-related successes (e.g., design decisions that paid off, effective testing strategies, fruitful data choices).
o	What were the personal learning successes that you experienced?

#### Complications and Setbacks
o	What Went Wrong or Was Hard
o	Concrete challenges or missteps (e.g., underestimated complexity, unstable training, bad initial data).
o	What would you do differently if you started over?
o	What were your personal learning obstacles during this project? How did you attempt to address them, and how would you fix them if you couldn't?


#### Algorithmic Lessons

o	Insights about your chosen algorithm/class in real use.
o	How well does it fit the problem?
o	Tradeoffs between accuracy, complexity, and implementation complexity.
o	Any surprises compared to how it was presented in the lecture or text?


#### Future Directions
o	Ideas for extending or improving the project (algorithm variants, better data, different evaluation methods, integration into larger pipelines).


#### Generative AI Disclosure
o	As before, include tool/version, prompts, and a transparent account of how you used generative AI, if applicable.
